### PR TITLE
feat: fix flashing avatar

### LINKED ISSUE #466: AN image flashed on the avatar place holder when the site is reloaded.
### Issue Description

Before I put an image on the student account, in the process of not being on it for a while and then reloading,  a pic flashes in the avatar place holder and then almost immediately, it disappears.

### Steps to Reproduce

_No response_

### Expected Behavior

The avatar placeholder should remain empty at all times till i put one there myself.

### Current Behavior

There are flashes of an image when I reload sometimes.

### Screenshots (optional)

_No response_

### Operating System [e.g., Windows 10]

Mac

### Browser [e.g., Chrome, Firefox]

Chrome

### Environment (locally, production, selfhosted)

_No response_

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

### PR DESCRIPTION
**Pull request by codiini**
## What does this PR do?

Fixes #466 

Before:
before-flash

After:
after-flash

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change adds a new database migration
- [ ] This change requires a documentation update

## How should this be tested?

- Go to profile settings page and refresh, there should be no sudden image flashes.

### Required

- [x] Filled out the "How to test" section in this PR
- [x] Self-reviewed my own code
- [ ] Commented on my code in hard-to-understand bits
- [ ] Ran `pnpm build`
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the ClassroomIO Docs if changes were necessary

### CODE REVIEW

File: apps/dashboard/src/lib/utils/store/user.ts [hunk 1]
```diff
@@ -38,8 +38,8 @@ export const defaultUserState: UserStore = {
 export const defaultProfileState: ProfileStore = {
   id: undefined,
   fullname: '',
-  avatar_url: 'https://pbs.twimg.com/profile_images/1416443682157473795/dGtFbtht_normal.jpg',
-  username: 'Elon',
```
Comment (rotimi-best) [inline apps/dashboard/src/lib/utils/store/user.ts:42]: okay can you attach a video showing what happens now without these defaults?

Comment (codiini) [reply apps/dashboard/src/lib/utils/store/user.ts:42]: @rotimi-best done

**Review by rotimi-best — APPROVED** [review]
LGTM, thank you @codiini
